baseURL: https://minimal-website.ch/
languageCode: fr
title: Minimalist Website

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

canonifyURLs: true
copyright: Creative Commons CC0
defaultContentLanguage: fr

disableFastRender: true

disableKinds: 
  - taxonomy
  - term

enableGitInfo: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      typographer: true
    parser:
      autoHeadingIDType: github-ascii


params:
  title: Minimal website
  description: Un site minimal, fonctionnel et efficace.
  footer: |
    Un site minimal, fonctionnel et efficace. 
    Abonnement par [flux RSS](/index.xml).
    Un projet de [Nicolas Friedli](https://nicolasfriedli.ch).  
    Réalisé avec [Hugo](https://gohugo.io/).
    Sources chez [GitHub](https://github.com/nfriedli/minimal-website.ch).
    Herbergé par [Netlify](https://www.netlify.com/).
    Sous licence Creative Commons CC0.
  images:
    - https://cdn.pixabay.com/photo/2019/02/04/12/18/winter-3974511_960_720.jpg